---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: registry-creds-controller
  name: registry-creds-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-creds-leader-election-role
  namespace: registry-creds-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: registry-creds-registry-creds-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ops.alexellis.io
  resources:
  - clusterpullsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.alexellis.io
  resources:
  - clusterpullsecrets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-creds-leader-election-rolebinding
  namespace: registry-creds-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-creds-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: registry-creds-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-creds-registry-creds-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-creds-registry-creds-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: registry-creds-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: registry-creds-controller
  name: registry-creds-registry-creds-controller
  namespace: registry-creds-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: registry-creds-controller
  template:
    metadata:
      labels:
        control-plane: registry-creds-controller
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        image: alexellis2/registry-creds-controller:0.2.0
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10