---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: stg
  labels:
    validate-image-signatures: "yes"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
