---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: image-signature-webhook
webhooks:
  - name: image-signature.mkorejo.com
    namespaceSelector:
      matchLabels:
        validate-image-signatures: "yes"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Ignore
    clientConfig:
      caBundle: "MIIDuDCCAqCgAwIBAgIUD+8t2o6z4Qz6kIE//9b1+J9quKowDQYJKoZIhvcNAQELBQAwYjELMAkGA1UEBhMCVVMxDzANBgNVBAgTBk9yZWdvbjERMA8GA1UEBxMIUG9ydGxhbmQxEDAOBgNVBAoTB0dyYWZlYXMxCzAJBgNVBAsTAkNBMRAwDgYDVQQDEwdHcmFmZWFzMB4XDTE3MTAxNjA2MTYwMFoXDTIyMTAxNTA2MTYwMFowYjELMAkGA1UEBhMCVVMxDzANBgNVBAgTBk9yZWdvbjERMA8GA1UEBxMIUG9ydGxhbmQxEDAOBgNVBAoTB0dyYWZlYXMxCzAJBgNVBAsTAkNBMRAwDgYDVQQDEwdHcmFmZWFzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvOJ/rxBvbVJDqglxE0QtzRmumLkeaArzeCARPx6G0et8Ho5wdyZA8MmHLjvTquKVedmqQHuC157f++VNnLuwf5MEZpmfPARtZUKlL4HYkBXPA4HUqLatjz827gcfXmzZMohlrk0b/aH53iZtZ4gLY8Px2ZxnJUn6fQNVtGLtdAf5BNYxCHRYcuCWduH4I+PPpOt3lIB/2XU5iCwrXjvZmoWsgK9/cYmIx78VDq7PB5+LvnjU5xiebPl4CH/mdSyfAVESbDu+tKtrPfGlvdNBvaV9Aq9AwabwaITAdANZihsbOhyw8Er4mJtk8UvKNrrL8SMObQ2T67G0j59pYiHxjwIDAQABo2YwZDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBAjAdBgNVHQ4EFgQUm7XoGXrbdIS4kWHfqwNHVPpBG6wwHwYDVR0jBBgwFoAUm7XoGXrbdIS4kWHfqwNHVPpBG6wwDQYJKoZIhvcNAQELBQADggEBAGIhEOtok44NByujVO2sEgbj5xuwDErDxQoytuK9qcTfbd86vlbJ258MUBm5U3/9L1k/gAsd3D02jGauCFjcxmb/fyvq3hreQqMEY2/+OWf3Hqs7T9EEfegpm/GGFkngVhFRXxgAW+WppQoZubq5NxISDQDjn0tymMiTPKl1yeiFF6jAFHkjQE4T40xJjNu7lJuFnwIWhwptYJupo49vbhbNN3fDAc2d8sj14rug9RxY90gTY2707bRdCunv5n5EcbV2I41L/vnlWdW/iUH2SvLDw8U5JdldWA90FtIJoU3ZkZktx+W10OPSzeW44t6kW2UgBfJoU1tZFD8sjBal9+g="
      service:
        name: image-signature-webhook
        namespace: adm