---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: image-signature-webhook
webhooks:
  - name: image-signature.mkorejo.com
    namespaceSelector:
      matchLabels:
        validate-image-signatures: "yes"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsRENDQW55Z0F3SUJBZ0lVQkFiMnlPZ1V2QXNSaHFiTGFLM25URlRGYmJ3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lqRUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEVEQU9CZ05WQkFvVEIwZHlZV1psWVhNeEN6QUpCZ05WQkFzVEFrTkJNUkF3RGdZRFZRUURFd2RICmNtRm1aV0Z6TUI0WERUSXdNVEF5TVRBd01ESXdNRm9YRFRJMU1UQXlNREF3TURJd01Gb3dZakVMTUFrR0ExVUUKQmhNQ1ZWTXhEekFOQmdOVkJBZ1RCazl5WldkdmJqRVJNQThHQTFVRUJ4TUlVRzl5ZEd4aGJtUXhFREFPQmdOVgpCQW9UQjBkeVlXWmxZWE14Q3pBSkJnTlZCQXNUQWtOQk1SQXdEZ1lEVlFRREV3ZEhjbUZtWldGek1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXQ1em1PVndmQVNna3lCc0U5Uk45dFJEVmM4Q3MKbWpGUVU2K240YzJqcit5eWtjSmVmQ0JkNVZNRkpBYnhhbUJqUkoxR0pHMVArOWQwUUIrcU5MWW9HYVZ6MU1HTgppbDlUMW43ZnJzWGFnejZXRlMrcDRYbGxkYjFhNFFxREJ5bXI1ejdLMG53ZjQzM3VOUjlWYlFOVmtRL3V4Zzl2Ck0yQ29CUnkxTlBxYWMzZ05uU3dOYUhnMDlsVVJJRmQ2SUtvTjNmNXRORENhTzNHWjdiM2QxcnBiSVpFZGlNOEQKR21kUUdqWVRreUFTK3NBQ3luUndWNmhnRWk2bnNlWkliclBOc0RPaUFjbUtLenBTeG5CV3dMajBFYThvYXdwbgovUjJRSEs5R2JJUjhOUDdRL0JFVkV5MllDc2VMenFsYW1WN0FsZmdscWtOTlE1dTQ0SmxwMlBkak9RSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKcndFWmV6WFFvN3RvQ0ZIWmhBUEJ6dnRDUEZjd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFaTdJajUxeVl1SgpwTW5yNnpici9GcVVWd2U3T3pjLzFEMm95K1pjbkQ5SkFkNFNkOEI5UzVRcWJmbnhYd2VHa2RBcVBtTms5ajRXCnFralpnMnNnV3ZiL0JKcmE0VjZBblNBOXgzYk82T1VBVHhON3lTbkk4b0RIZnJhRmE5d0ltbkJxZDFuWjU0VHYKMXIwRHFFb3B3VkwyV1lleENDdjFMQ2x2blY1NXA2L2h3S2d4TlhQZ0VNWThDaTNMYVZzZUhiWVhHZ2VIZ3F4TQo0bDN0TnJhbkJQNEIvK05GUE9vblNnRUFVdVRLY0t1Z1ZyV1oyYWlNYnNsZTFJMGZzSFNwdGdDQmpDZ2UxTXAzCkhaNExBTzlsdEZESFR1NlV1aHd1NzlzbWdlaEk4eTI4ZFZQcjgrVkpYcjV6K0lEbDByNmt0VkVGWTVhVlFaZ0wKM3VnVitnQ1BMcHM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      service:
        name: image-signature-webhook
        namespace: adm