---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafeas
  namespace: adm
spec:
  releaseName: grafeas
  chart:
    git: git@github.com:grafeas/grafeas
    path: grafeas-charts
    ref: v0.1.6
  values:
    container:
      port: 5000
    certificates:
      enabled: false
      name: grafeas-self-signed
      ca:
      cert:
      key:
    secret:
      enabled: false
    service:
      port: 5000