---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafeas
  name: grafeas
  namespace: adm
spec:
  ports:
    - name: http
      port: 8080
      protocol: "TCP"
  selector:
    app: grafeas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafeas
  namespace: adm
spec:
  selector:
    matchLabels:
      app: grafeas
  template:
    metadata:
      labels:
        app: grafeas
    spec:
      containers:
        - name: grafeas
          image: "gcr.io/hightowerlabs/grafeas:0.0.1"
          imagePullPolicy: Always