---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafeas
  namespace: adm
spec:
  releaseName: grafeas
  chart:
    git: git@github.com:grafeas/grafeas
    path: grafeas-charts
    ref: v0.1.6
  values:
    container:
      port: 5000
    certificates:
      enabled: false
      name: grafeas-self-signed
      ca:
      cert:
      key:
    secret:
      enabled: false
    service:
      port: 5000
---
apiVersion: v1
kind: Ingress
metadata:
  name: grafeas
  namespace: adm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-route53
    kubernetes.io/ingress.class: nginx-public
spec:
  rules:
  - host: grafeas.devops.coda.run
    http:
      paths:
      - backend:
          serviceName: grafeas-server
          servicePort: 5000
        path: /
  tls:
  - hosts:
    - grafeas.devops.coda.run
    secretName: grafeas-tls
